feat:新增大数据开发实践文档
pyloong/pythonic-project-guidelines pull request #26
Opened 2022-09-05 09:24 UTC by JingyuanR

- 新增 `基础--前期准备` 文档
- 新增 `基础--快速上手` 文档

2022-09-05 10:27 UTC, whg517 requested changes
Reviewed:

- 文档中有些错别字
- 示例项目代码没有格式化和风格检查

2022-09-05 10:27 UTC, whg517 commented on docs/bigdata/basis/quick_start.md
> +若使用[poetry](/pythonic-project-guidelines/introduction/virtualenv/#25-poetry)，`pyproject.toml`文件增加：
这句话读起来好像有点不通顺，而且项目本身就默认采用了 poetry 管理虚拟环境，是否可以改成 `因为项目默认使用[poetry](/pythonic-project-guidelines/introduction/virtualenv/#25-poetry) 管理虚拟环境，则需要在 `pyproject.toml` 文件增加中增加如下内容：`

2022-09-05 10:27 UTC, whg517 commented on docs/bigdata/basis/quick_start.md
> +开发环境需要初始化插件：
这句话表达的较为模糊。可以改成 `使用如下命令将项目插件更新到环境中：`

2022-09-05 10:27 UTC, whg517 commented on docs/bigdata/basis/quick_start.md
> +`src/etl_project/tasks/car_etl_example/task.py`
可以放在一行

2022-09-05 10:27 UTC, whg517 commented on docs/bigdata/basis/quick_start.md
> +from etl_project.tasks.car_etl_example.car_transform import CarTransform
示例项目是否执行过 isort ？ 请检查是否符合 [风格规范-3.13 导入格式](https://pyloong.github.io/pythonic-project-guidelines/standard/style_rules/#313)

2022-09-05 10:27 UTC, whg517 commented on docs/bigdata/basis/quick_start.md
> +每一个`Task`任务都会经理“输入”、“转换”和“输出”的过程，实现AbstractTask中的`_input`、`_transform`、`_output`抽象方法
错别字：`经理` 。 `AbstractTask ` 建议使用 `包裹。

2022-09-05 10:27 UTC, whg517 commented on docs/bigdata/basis/quick_start.md
> +from etl_project.tasks.abstract.transform import AbstractTransform
没有进行导入分层，不符合 PEP 8规范

2022-09-05 10:27 UTC, whg517 commented on docs/bigdata/basis/quick_start.md
> +4. 返回数据结果，至此完成汽车数据转换过程
添加处理该逻辑的方法。例如 `_filter_price` 的功能是筛选 `price` > 10000 的数据

2022-09-05 10:27 UTC, whg517 commented on docs/bigdata/basis/quick_start.md
> +        self.logger.warn(f'Load data to {self.output_path}')
代码应该没有进行风格检查，方法缺少注释，包括后续代码也是

2022-09-05 10:27 UTC, whg517 commented on docs/bigdata/basis/quick_start.md
> +这么做的目的是将 `CarDataTask` 注册到 `entry_points` 中， 然后在程序中使用 `import.metadata`
[使用 importlib.metadata](https://docs.python.org/zh-cn/3/library/importlib.metadata.html)

2022-09-05 10:27 UTC, whg517 commented on docs/bigdata/basis/quick_start.md
> +
既然已经将命令行注册，为何不直接使用命令行？

2022-09-06 06:12 UTC, JingyuanR commented on docs/bigdata/basis/quick_start.md
> +
`cmdline`后续增加命令行功能

2022-09-06 07:44 UTC, whg517 approved these changes

2022-09-07 01:47 UTC, whg517 commented
#27

2022-09-07 01:48 UTC, merged