feat: 代码风格和语言规范更新
pyloong/pythonic-project-guidelines pull request #33
Opened 2023-06-29 06:59 UTC by qiang1218

2023-06-29 09:51 UTC, whg517 requested changes
review language rules

2023-06-29 09:51 UTC, whg517 commented on docs/standard/language_rules.md
> +新的语言版本的语义变化可能会通过特殊的 future import 进行控制，以便在早期的运行时环境中以文件为基础启用它们。
可以使用导入 future 这种特殊操在老版本中使用新版本的语法特性

2023-06-29 09:51 UTC, whg517 commented on docs/standard/language_rules.md
> +能够通过 `from __future__ import` 语句打开一些更现代的功能，可以尽早使用预期的未来 Python 版本中的功能。
使用 `from __future__ import` 语句可以在老版本中启用新版本的功能。

2023-06-29 09:51 UTC, whg517 commented on docs/standard/language_rules.md
> +- 现代代码更易于维护，因为它不太可能积累技术债务，而技术债务在未来的运行时升级期间会出现问题。
经验证明，在声明兼容性并防止这些文件中的回归的同时，对每个文件进行更改，可以使运行时版本升级更加平滑。现代代码更易于维护，因为它不太可能在将来的运行时升级期间积累技术债务。

2023-06-29 09:51 UTC, whg517 commented on docs/standard/language_rules.md
> +- 在引入所需的 future 语句之前，此类代码可能无法在非常旧的解释器版本上运行。
没有引入所需的 future 语句时，这些代码可能无法在老版本的解释器版本上运行。

2023-06-29 09:51 UTC, whg517 commented on docs/standard/language_rules.md
> +- 在支持极其广泛的环境的项目中，这种需求更为常见。
在支持各种环境的项目中，这种需求更为常见。

2023-06-29 09:51 UTC, whg517 commented on docs/standard/language_rules.md
> +的导入，以便在有人开始使用这些特性时，不会在以后的编辑中忘记它们。
不要删除这些导入，除非您确信代码在当前环境运行没有问题。即使您现在没有使用当前代码中特定的 future 导入启用的特性，保留这些导入便于以后修改代码时直接使用。

2023-06-29 09:51 UTC, whg517 commented on docs/standard/language_rules.md
> +和 [the print function](https://www.python.org/dev/peps/pep-3105/)。
有关更多信息，请阅读 [Python future](https://docs.python.org/3/library/__future__.html) 语句定义文档。

2023-06-29 09:51 UTC, whg517 commented on docs/standard/language_rules.md
> +这些库就是为了让代码实现更清晰简单而存在的。
删除

2023-07-03 01:36 UTC, qiang1218 commented on docs/standard/language_rules.md
> +新的语言版本的语义变化可能会通过特殊的 future import 进行控制，以便在早期的运行时环境中以文件为基础启用它们。
已调整

2023-07-03 01:37 UTC, qiang1218 commented
已调整

2023-07-07 02:34 UTC, merged